=== catink123/zuma-clone/assets/xml-define/level.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:attributeGroup name="vec2">
    <xs:attribute name="x" type="xs:float" use="required"/>
    <xs:attribute name="y" type="xs:float" use="required"/>
  </xs:attributeGroup>

  <xs:element name="level">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="background">
          <xs:complexType>
            <xs:attribute name="src" type="xs:anyURI" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="player-position">
          <xs:complexType>
            <xs:attributeGroup ref="vec2"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="ball-count" type="xs:integer" />
        <xs:element name="speed-multiplier" type="xs:float" />
        <xs:element name="point" maxOccurs="unbounded" minOccurs="2">
          <xs:complexType>
            <xs:attributeGroup ref="vec2"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== catink123/zuma-clone/assets/levels/level1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xml-define/level.xsl"?>

<level
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../xml-define/level.xsd">
  <name>Level 1</name>
  <background src="level1.png" />
  <player-position x="615" y="330"/>
  <ball-count>15</ball-count>
  <speed-multiplier>1</speed-multiplier>

  <point x="86" y="4" />
  <point x="79" y="32" />
  <point x="75" y="69" />
  <point x="78" y="117" />
  <point x="96" y="157" />
  <point x="129" y="190" />
  <point x="172" y="206" />
  <point x="220" y="211" />
  <point x="318" y="209" />
  <point x="474" y="209" />
  <point x="597" y="211" />
  <point x="700" y="212" />
  <point x="836" y="207" />
  <point x="971" y="201" />
  <point x="1063" y="203" />
  <point x="1103" y="214" />
  <point x="1122" y="225" />
  <point x="1133" y="242" />
  <point x="1144" y="268" />
  <point x="1147" y="307" />
  <point x="1142" y="351" />
  <point x="1127" y="391" />
  <point x="1092" y="417" />
  <point x="1039" y="430" />
  <point x="981" y="435" />
  <point x="914" y="443" />
  <point x="821" y="447" />
  <point x="775" y="441" />
  <point x="728" y="448" />
  <point x="664" y="450" />
  <point x="504" y="454" />
  <point x="448" y="452" />
  <point x="348" y="454" />
  <point x="253" y="458" />
  <point x="221" y="461" />
  <point x="192" y="473" />
  <point x="168" y="495" />
  <point x="156" y="515" />
  <point x="153" y="538" />
  <point x="156" y="564" />
  <point x="169" y="592" />
  <point x="191" y="611" />
  <point x="217" y="618" />
  <point x="259" y="618" />
  <point x="331" y="618" />
  <point x="398" y="613" />
  <point x="466" y="614" />
  <point x="535" y="617" />
  <point x="601" y="615" />
  <point x="665" y="614" />
  <point x="728" y="614" />
  <point x="783" y="613" />
  <point x="850" y="613" />
  <point x="915" y="612" />
  <point x="972" y="611" />
  <point x="1024" y="608" />
  <point x="1079" y="606" />
  <point x="1161" y="609" />
</level>
